spring.application.name=ai-support-platform

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/ai_support_platform?sslmode=disable
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#auth
jwt.secret=9f4d2c8a7b1e5f93c6d8a2e7b4f1c9d5e8a3f7b2c6d1e9a4f8b5c2d7a1e6f3b9
gemini.api.key=AIzaSyDUkPzRhmX0BWNlWDyXVFbMcgav3dKjF7E